# filepath: .github/workflows/deploy.yml
name: Deploy MkDocs to GitHub Pages
on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/pypoetry/bin" >> $GITHUB_PATH

      # Install dependencies
      - name: Install dependencies
        run: 
          poetry install --no-root

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use the GitHub token for authentication
        run: | 
          poetry run mkdocs build
          rm -rf docs
          mv site docs
          git config user.name "github-actions[bot]"
          git config user.mail "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/EuclidsToolworks/EuclidsToolworks.github.io.git
          git add docs
          git commit -m "Deploy site to GitHub Pages"
          git push origin main
